"""Generate a first numerical report for the Version 1 solver core.

This script is intentionally lightweight and deterministic enough for a research
notebook/report artifact. Runtime values are approximate and hardware-dependent.
"""

from __future__ import annotations

import csv
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from solver.config import GridParams, PhysicalParams, SpaceChargeParams
from solver.electrostatics import solve_laplace
from solver.fields import compute_electric_field
from solver.geometry import rectangular_electrodes
from solver.grid import AxisymmetricGrid
from solver.interface import GraphInterface
from solver.residual import compute_residual
from solver.space_charge import shielding_metric, solve_gaussian_shielding
from solver.verification import run_quartic_manufactured_poisson, taylor_cone_half_angle_deg


def main() -> None:
    out_dir = ROOT / "results"
    out_dir.mkdir(exist_ok=True)

    alpha = taylor_cone_half_angle_deg()

    manufactured_sizes = [(25, 27), (49, 53), (97, 105)]
    manufactured = [run_quartic_manufactured_poisson(nr, nz) for nr, nz in manufactured_sizes]
    csv_path = out_dir / "v1_manufactured_convergence.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["nr", "nz", "l2_error", "linf_error", "nnz", "solve_seconds"])
        for r in manufactured:
            writer.writerow([r.nr, r.nz, f"{r.l2_error:.16e}", f"{r.linf_error:.16e}", r.nnz, f"{r.solve_seconds:.8f}"])

    # Voltage scaling sanity check.
    grid = AxisymmetricGrid.from_params(GridParams(r_max=1.0, z_min=0.0, z_max=1.0, nr=41, nz=41))
    masks = rectangular_electrodes(grid, powered="z_max", ground="z_min", far_dirichlet=False)
    phi_500 = solve_laplace(grid, masks, PhysicalParams(V0=500.0))
    phi_1000 = solve_laplace(grid, masks, PhysicalParams(V0=1000.0))
    _, _, E_500 = compute_electric_field(grid, phi_500)
    _, _, E_1000 = compute_electric_field(grid, phi_1000)
    interior = np.s_[1:-1, 1:-1]
    voltage_ratio = float(np.median(E_1000[interior] / E_500[interior]))
    pressure_ratio = float((np.median(E_1000[interior]) / np.median(E_500[interior])) ** 2)

    # Residual null sanity: cylinder with no field has constant capillary pressure
    # fully removed by mean Delta_p subtraction.
    z = np.linspace(0.2, 0.8, 41)
    cylinder = GraphInterface(z=z, R=np.full_like(z, 0.25))
    zeros = np.zeros(grid.shape)
    residual_diag = compute_residual(grid, cylinder, zeros, zeros, PhysicalParams(gamma=0.022))

    # Gaussian run: report convergence and also demonstrate why ROI metrics matter.
    sg_params = SpaceChargeParams(
        model="gaussian",
        rho0=1e-10,
        ell=0.2,
        apex_r=0.0,
        apex_z=0.5,
        relaxation=0.8,
        tolerance=1e-7,
        max_iterations=50,
    )
    sg_result = solve_gaussian_shielding(grid, masks, PhysicalParams(V0=100.0), sg_params)
    roi = (grid.R < 0.25) & (np.abs(grid.Z - 0.5) < 0.25)
    phi_ref = solve_laplace(grid, masks, PhysicalParams(V0=100.0))
    _, _, E_ref = compute_electric_field(grid, phi_ref)
    global_metric = shielding_metric(sg_result.E_mag, E_ref)
    roi_metric = shielding_metric(sg_result.E_mag, E_ref, mask=roi)

    report = out_dir / "v1_numerical_report.md"
    report.write_text(
        f"""# Version 1 Numerical Report

Generated by `scripts/generate_v1_report.py`.

## 1. Classical Taylor angle benchmark

Computed from the Legendre-root condition:

```math
P_{{1/2}}(\\cos\\vartheta_0)=0, \\quad \\alpha = 180^\\circ - \\vartheta_0
```

Result:

```text
alpha = {alpha:.10f} degrees
```

This reproduces the classical Taylor half-angle.

## 2. Manufactured Poisson convergence

Manufactured solution:

```math
\\phi(r,z)=r^4+z^4+r^2z^2
```

Axisymmetric Laplacian:

```math
\\nabla^2\\phi = 18r^2 + 16z^2
```

Dirichlet values are imposed on `z_min`, `z_max`, and `r_max`; the `r=0` axis
interior rows are left to the special regularity stencil.

| Grid | L2 error | Linf error | nnz | solve seconds |
|---:|---:|---:|---:|---:|
"""
        + "".join(
            f"| {r.nr} x {r.nz} | {r.l2_error:.3e} | {r.linf_error:.3e} | {r.nnz} | {r.solve_seconds:.4f} |\n"
            for r in manufactured
        )
        + f"""
CSV artifact: `results/v1_manufactured_convergence.csv`

## 3. Voltage scaling sanity check

Parallel-plate Laplace case with `V0=500 V` and `V0=1000 V`.

```text
median |E|(1000 V) / |E|(500 V) = {voltage_ratio:.10f}
implied Maxwell pressure ratio      = {pressure_ratio:.10f}
```

Expected values are approximately 2 and 4 respectively.

## 4. Residual null sanity check

For a cylindrical interface with zero electric field, capillary pressure is
constant and should be removed by the mean `Delta_p` subtraction.

```text
Delta_p = {residual_diag.delta_p:.12e} Pa
RMS residual = {residual_diag.rms_residual:.12e} Pa
max |residual| = {residual_diag.max_abs_residual:.12e} Pa
```

## 5. Gaussian space-charge scaffold

This confirms that the Gaussian Poisson-source scaffold converges. It is not
yet a physical emission-current model.

```text
converged = {sg_result.converged}
iterations = {sg_result.iterations}
global S_E = {global_metric:.12e}
apex-local ROI S_E = {roi_metric:.12e}
```

Important caveat: the global `S_E` can be dominated by electrode/far-boundary
peaks. For serious shielding claims, use an apex-local region-of-interest and
validate the sign/closure against measurements or a transport model.
"""
    )
    print(f"Wrote {report}")
    print(f"Wrote {csv_path}")


if __name__ == "__main__":
    main()
